[[apps]]
folder = "conway"
application_name = "conway"
application_version = "1.0.0"
application_descriptions = "Conway's Game of Life Simulator."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "conway/main.py", "conway/app.toml",]

[[apps]]
folder = "hello"
application_name = "hello"
application_version = "1.0.0"
application_descriptions = "Basic test to power on the display."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "hello/main.py", "hello/app.toml",]

[[apps]]
folder = "tomato"
application_name = "tomato"
application_version = "1.0.0"
application_descriptions = "Pomodoro Timer: 25-min work, 5-min break."
author_name = "Sipeed-bugu"
interaction_requires_user_input = false
files = [ "tomato/main.py", "tomato/app.toml",]

[[apps]]
folder = "coin"
application_name = "coin"
application_version = "1.0.0"
application_descriptions = "Stock Market Viewer Demo."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "coin/main.py", "coin/app.toml",]

[[apps]]
folder = "drawo"
application_name = "drawo"
application_version = "1.0.0"
application_descriptions = "A drawing board that can be used for drawing on a touchscreen"
author_name = "Sipeed-iaw9lkm"
interaction_requires_user_input = true
files = [ "drawo/main.py", "drawo/app.toml",]

[[apps]]
folder = "samba"
application_name = "samba"
application_version = "1.0.0"
application_descriptions = "Enable a Samba server for file transfer."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "samba/main.py", "samba/framebuffer.py","samba/input.py","samba/samba.py","samba/app.toml",]

[[apps]]
folder = "PWR-BTN"
application_name = "PWR-BTN"
application_version = "1.0.0"
application_descriptions = "Monitor the host's power status and manage power and reset operations."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "PWR-BTN/main.py", "PWR-BTN/framebuffer.py","PWR-BTN/input.py","PWR-BTN/atx.py","PWR-BTN/app.toml",]

[[apps]]
folder = "serial"
application_name = "serial"
application_version = "1.0.0"
application_descriptions = "A simple serial display terminal."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "serial/main.py", "serial/framebuffer.py","serial/input.py","serial/uart.py","serial/app.toml",]
