[[apps]]
folder = "serial"
application_name = "serial"
application_version = "1.0.0"
application_descriptions = "A simple serial display terminal."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "serial/framebuffer.py", "serial/app.toml", "serial/uart.py", "serial/input.py", "serial/main.py",]

[[apps]]
folder = "hello"
application_name = "hello"
application_version = "1.0.0"
application_descriptions = "Basic test to power on the display."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "hello/app.toml", "hello/main.py",]

[[apps]]
folder = "PWR-BTN"
application_name = "PWR-BTN"
application_version = "1.0.0"
application_descriptions = "Monitor the host's power status and manage power and reset operations."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "PWR-BTN/atx.py", "PWR-BTN/framebuffer.py", "PWR-BTN/app.toml", "PWR-BTN/input.py", "PWR-BTN/main.py",]

[[apps]]
folder = "tomato"
application_name = "tomato"
application_version = "1.0.0"
application_descriptions = "Pomodoro Timer: 25-min work, 5-min break."
author_name = "Sipeed-bugu"
interaction_requires_user_input = false
files = [ "tomato/app.toml", "tomato/main.py",]

[[apps]]
folder = "drawo"
application_name = "drawo"
application_version = "1.0.0"
application_descriptions = "A drawing board that can be used for drawing on a touchscreen"
author_name = "Sipeed-iaw9lkm"
interaction_requires_user_input = true
files = [ "drawo/app.toml", "drawo/main.py",]

[[apps]]
folder = "coin"
application_name = "coin"
application_version = "1.0.0"
application_descriptions = "Stock Market Viewer Demo."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "coin/app.toml", "coin/main.py",]

[[apps]]
folder = "conway"
application_name = "conway"
application_version = "1.0.0"
application_descriptions = "Conway's Game of Life Simulator."
author_name = "Sipeed-zepan"
interaction_requires_user_input = false
files = [ "conway/app.toml", "conway/main.py",]

[[apps]]
folder = "HW-UP"
application_name = "HW-UP"
application_version = "1.0.0"
application_descriptions = "Update some hardware firmware"
author_name = "Sipeed-bugu"
interaction_requires_user_input = true
files = [ "HW-UP/app.toml", "HW-UP/nanokvm_update_86102", "HW-UP/README.md", "HW-UP/main.py", "HW-UP/nanokvm_86102R2[43].bin",]

[[apps]]
folder = "samba"
application_name = "samba"
application_version = "1.0.0"
application_descriptions = "Enable a Samba server for file transfer."
author_name = "Sipeed-916BGAI"
interaction_requires_user_input = true
files = [ "samba/framebuffer.py", "samba/app.toml", "samba/samba.py", "samba/README.md", "samba/input.py", "samba/main.py",]

